#!/bin/sh

xpath() {
  json=$1; shift
  echo "$json" | jq -c $@
}

PATH=$PATH:/root/google-cloud-sdk/bin:$GOPATH/bin

LOG_PATH=/logs/initials
mkdir -p $LOG_PATH

gcloud auth activate-service-account --key-file=/secrets/gcs/service-account.json
gcloud --quiet auth configure-docker

go get -u github.com/golang/dep/cmd/dep

src_root=`xpath "$DOCKERIZE_OPTIONS" -r ".src_root"`
for x in `xpath "$DOCKERIZE_OPTIONS" ".refs[]"`; do
  path_alias=`xpath "$x" -r ".path_alias"`
  clone_path="$src_root/src/$path_alias"
  cd $clone_path && {
    sha=`git log -1 --format="%h"`
    dep ensure -v
    make 2>&1 | tee -a $LOG_PATH/docker-build.txt
  }
done

docker image prune -f -a --filter "until=1h"

